REQUEST_ID_LENGTH = 10

ALLOWED_CONNECTION_SCHEMES = ['http', 'https', 'ws', 'wss']
HTTP_CONNECTION_SCHEMES = ['http', 'https']
WS_CONNECTION_SCHEMES = ['ws', 'wss']

DEFAULT_CONNECTION_URL = "http://127.0.0.1:8000"

WS_REQUEST_TIMEOUT = 10  # seconds

UNSUPPORTED_HTTP_METHODS = ["kill", "live"]
